### PR TITLE
Add documentation for `@revise`

### PR DESCRIPTION
**Pull request by rikhuijzer**
Feel free to change the text

### CODE REVIEW

**Comment by Pangoraw** [comment]
Thanks @rikhuijzer! what do you think about making the documentation out of Pluto notebooks (in a `docs` folder instead) ?
We can then link to the static export from the readme

**Comment by rikhuijzer** [comment]
Yeah sounds fine :+1:

**Comment by fonsp** [comment]
@Pangoraw can you do a release?

**Comment by rikhuijzer** [comment]
> Thanks @rikhuijzer! what do you think about making the documentation out of Pluto notebooks (in a `docs` folder instead) ? We can then link to the static export from the readme

The end result looks great! :balloon: :+1:

**Comment by Pangoraw** [comment]
> @Pangoraw can you do a release?

Why ? There was [no functional change](https://github.com/JuliaPluto/PlutoLinks.jl/compare/v0.1.3...main) since 0.1.3.

**Pull request merged**
